#数据源
spring:
  devtools:
      restart:
        additional-paths:
        - src/main/java
  datasource:
    #四大金刚
    url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf-8
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    #防火墙过滤器
    filters: stat,wall,log4j
    #初始化数量
    initialSize: 5
    #最大并发
    maxActive: 20
    #最大预处理链接数量
    maxPoolPreparedStatementPerConnectionSize: 20
    #最大等待时间
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    #最小初始化数量
    minIdle: 5
    #是否开启预处理对象缓存池
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    #检查SQL语句
    validationQuery: SELECT 1 FROM DUAL
  #视图解析器
  mvc:
    view:
      prefix: /
      suffix: .jsp
  
  #redis配置
#  redis:
#    #默认使用数据库
#    database: 0
#    #redis链接地址
#    host: 172.20.10.3
#    #链接密码
#    password: 
#    #访问超时
#    timeout: 3000
#      
#服务端配置
server:
  servlet:
    #项目名称必须以/开头
    context-path: /lmovie
    #设置开发模式
    jsp:
      init-parameters:
          development: true
  
  
